import {RepoResult} from "./useRepoSearch";

const a = {
    "id": 5216913,
    "node_id": "MDEwOlJlcG9zaXRvcnk1MjE2OTEz",
    "name": "facebook",
    "full_name": "huandu/facebook",
    "private": false,
    "owner": {
        "login": "huandu",
        "id": 239739,
        "node_id": "MDQ6VXNlcjIzOTczOQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/239739?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/huandu",
        "html_url": "https://github.com/huandu",
        "followers_url": "https://api.github.com/users/huandu/followers",
        "following_url": "https://api.github.com/users/huandu/following{/other_user}",
        "gists_url": "https://api.github.com/users/huandu/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/huandu/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/huandu/subscriptions",
        "organizations_url": "https://api.github.com/users/huandu/orgs",
        "repos_url": "https://api.github.com/users/huandu/repos",
        "events_url": "https://api.github.com/users/huandu/events{/privacy}",
        "received_events_url": "https://api.github.com/users/huandu/received_events",
        "type": "User",
        "site_admin": false
    },
    "html_url": "https://github.com/huandu/facebook",
    "description": "A Facebook Graph API SDK For Go.",
    "fork": false,
    "url": "https://api.github.com/repos/huandu/facebook",
    "forks_url": "https://api.github.com/repos/huandu/facebook/forks",
    "keys_url": "https://api.github.com/repos/huandu/facebook/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/huandu/facebook/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/huandu/facebook/teams",
    "hooks_url": "https://api.github.com/repos/huandu/facebook/hooks",
    "issue_events_url": "https://api.github.com/repos/huandu/facebook/issues/events{/number}",
    "events_url": "https://api.github.com/repos/huandu/facebook/events",
    "assignees_url": "https://api.github.com/repos/huandu/facebook/assignees{/user}",
    "branches_url": "https://api.github.com/repos/huandu/facebook/branches{/branch}",
    "tags_url": "https://api.github.com/repos/huandu/facebook/tags",
    "blobs_url": "https://api.github.com/repos/huandu/facebook/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/huandu/facebook/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/huandu/facebook/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/huandu/facebook/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/huandu/facebook/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/huandu/facebook/languages",
    "stargazers_url": "https://api.github.com/repos/huandu/facebook/stargazers",
    "contributors_url": "https://api.github.com/repos/huandu/facebook/contributors",
    "subscribers_url": "https://api.github.com/repos/huandu/facebook/subscribers",
    "subscription_url": "https://api.github.com/repos/huandu/facebook/subscription",
    "commits_url": "https://api.github.com/repos/huandu/facebook/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/huandu/facebook/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/huandu/facebook/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/huandu/facebook/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/huandu/facebook/contents/{+path}",
    "compare_url": "https://api.github.com/repos/huandu/facebook/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/huandu/facebook/merges",
    "archive_url": "https://api.github.com/repos/huandu/facebook/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/huandu/facebook/downloads",
    "issues_url": "https://api.github.com/repos/huandu/facebook/issues{/number}",
    "pulls_url": "https://api.github.com/repos/huandu/facebook/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/huandu/facebook/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/huandu/facebook/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/huandu/facebook/labels{/name}",
    "releases_url": "https://api.github.com/repos/huandu/facebook/releases{/id}",
    "deployments_url": "https://api.github.com/repos/huandu/facebook/deployments",
    "created_at": "2012-07-28T19:05:56Z",
    "updated_at": "2021-09-03T10:29:45Z",
    "pushed_at": "2021-04-30T03:47:52Z",
    "git_url": "git://github.com/huandu/facebook.git",
    "ssh_url": "git@github.com:huandu/facebook.git",
    "clone_url": "https://github.com/huandu/facebook.git",
    "svn_url": "https://github.com/huandu/facebook",
    "homepage": "",
    "size": 384,
    "stargazers_count": 996,
    "watchers_count": 996,
    "language": "Go",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 369,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
    },
    "forks": 369,
    "open_issues": 1,
    "watchers": 996,
    "default_branch": "master",
    "score": 1.0
}
export const mock = {
    "total_count": 161297,
    "incomplete_results": false,
    "items": new Array(10).fill(a),
}